### ISSUE TITLE
【Bug】远控刷新问题

### ISSUE THREAD

**Issue by JayWenStar** [SonicCloudOrg/sonic-server#100]
**Bug 描述**
进入远控后，没隔一次刷新都会有一次黑屏，原因是刷新是旧socket的close和新socket的start逻辑同时进行导致冲突，目前通过加锁解决。 

**版本**
Sonic的版本号 | 1.2.0-release

**Comment by mimajiushi** [comment]
多了行奇怪的sendtext。。

**Comment by ZhouYixun** [comment]
并入测试
