### ISSUE TITLE
【Bug】集群版本，远控卡顿

### ISSUE THREAD

**Issue by Felix1029** [SonicCloudOrg/sonic-server#118]
**Bug 描述**
集群版本
v1.3.0-beta2

远控时会很卡顿，目前我只连接了一台手机， 换了几台都是这样。 不知提供些什么日志，可以定位问题？
 

**版本**
  #@Sonic的版本号：v1.3.0-beta2new
部署的系统。 mac

**Comment by JayWenStar** [comment]
如果可以的话，找一个应用市场都能下到的、并且能出现明显卡顿的app，我们会尝试用来调试下

**Comment by JayWenStar** [comment]
以及提供下测试手机的型号

**Comment by JayWenStar** [comment]
其实这个问题也不是第一次反馈了，预计明后两天会排查下

**Comment by ZhouYixun** [comment]
请问什么机型？

**Comment by Felix1029** [comment]
> 以及提供下测试手机的型号

我试了 小米mi 5x，  redmi note8、 meizu18pro。   滑动屏幕的时候刚开始好些，过会延迟就来了，minitouch 没什么延迟，就是图像开始延迟。 可以试试高德地图， 或者浏览器播个视频。  尤其是关闭应用回到桌面时，那个动画

**Comment by Felix1029** [comment]
一个局域网会有偶现， 跨网段访问出现概率大，大佬们应该没在一起工作吧，可以跨网段试试

**Comment by JayWenStar** [comment]
@Felix1029 Get

**Comment by JayWenStar** [comment]
> 一个局域网会有偶现， 跨网段访问出现概率大，大佬们应该没在一起工作吧，可以跨网段试试

如果可以，希望再补充个小录屏到社区，mac下按`command+shift+5即可录屏`，社区可以上传20MB以内的视频

**Comment by Felix1029** [comment]
社区那个回复是不是关闭了？ 我远控的机子是mac-pro I5，16GB内存。   agent的那台机器是mac-pro I7 32GB。
你视频里显示cpu占比的命令是啥？  我是用mac的活动监视器，等会儿我录个视频。 我看你操作的应该是从agent 那台机器去远控的吧？

**Comment by JayWenStar** [comment]
> 社区那个回复是不是关闭了？ 我远控的机子是mac-pro I5，16GB内存。 agent的那台机器是mac-pro I7 32GB。 你视频里显示cpu占比的命令是啥？ 我是用mac的活动监视器，等会儿我录个视频。 我看你操作的应该是从agent 那台机器去远控的吧？

回复重新开了

**Comment by JayWenStar** [comment]
> 社区那个回复是不是关闭了？ 我远控的机子是mac-pro I5，16GB内存。 agent的那台机器是mac-pro I7 32GB。 你视频里显示cpu占比的命令是啥？ 我是用mac的活动监视器，等会儿我录个视频。 我看你操作的应该是从agent 那台机器去远控的吧？

跨网段不行我理解应该是受到网络环境影响，居家网络一般都是下行速度很快，但上行速度很慢

**Comment by Felix1029** [comment]
然后，cpu 有时也会到100%， 刚开始还可以，过会儿马上就延迟很高。 我压缩了视频，96M传不上去。  顺便问一下，社区能改自己的
名字么？没找到修改的地方

**Comment by JayWenStar** [comment]
> 然后，cpu 有时也会到100%， 刚开始还可以，过会儿马上就延迟很高。 我压缩了视频，96M传不上去。 顺便问一下，社区能改自己的 名字么？没找到修改的地方

只录卡顿那一段就够了，修改名字没有开启，注册的时候就定了，跟github类似

**Comment by JayWenStar** [comment]
> 社区那个回复是不是关闭了？ 我远控的机子是mac-pro I5，16GB内存。 agent的那台机器是mac-pro I7 32GB。 你视频里显示cpu占比的命令是啥？ 我是用mac的活动监视器，等会儿我录个视频。 我看你操作的应该是从agent 那台机器去远控的吧？

排查到了，跨网段时对agent机器上行带宽要求较高，出现画面延迟是因为agent机器带宽不足

**Comment by JayWenStar** [comment]
> 社区那个回复是不是关闭了？ 我远控的机子是mac-pro I5，16GB内存。 agent的那台机器是mac-pro I7 32GB。 你视频里显示cpu占比的命令是啥？ 我是用mac的活动监视器，等会儿我录个视频。 我看你操作的应该是从agent 那台机器去远控的吧？

排查到了，受带宽影响，暂时没有优化空间，只能是用户自己提升带宽，排查视频见社区，这里先close掉了

**Comment by JayWenStar** [comment]
@Felix1029 另外，社区开启更改昵称了

**Comment by Felix1029** [comment]
> @Felix1029 另外，社区开启更改昵称了

在设置里么？只看到更改密码，更改邮箱
