### ISSUE TITLE
【优化】公共步骤的一些优化建议

### ISSUE THREAD

**Issue by LiuJingtest** [SonicCloudOrg/sonic-server#122]
1. 公共步骤可以引用其他公共步骤，减少同样的步骤在多个公共步骤或者用例里使用，便于维护
2. 公共步骤可以增加参数化，是提供给用例的时候，增加参数。类似与编程的函数，写一个登录的公共步骤，可以提供username 和 password 出去，便于不同用例可以使用不同账户登录。

**Comment by ZhouYixun** [comment]
两个都有了，你仔细研究下
