### ISSUE TITLE
【question】没完全开源？

### ISSUE THREAD

**Issue by aerfa2022** [SonicCloudOrg/sonic-server#123]
看 https://github.com/SonicCloudOrg/sonic-plugin-android 里的代码与实际功能对不上，公司风险部不给用。

**Comment by ZhouYixun** [comment]
那个是另一个插件，已经废弃了，目前的apk会下个版本开源，会加上新功能，感谢关注

**Comment by aerfa2022** [comment]
> 那个是另一个插件，已经废弃了，目前的apk会下个版本开源，会加上新功能，感谢关注

感谢回复，期待~

**Comment by ZhouYixun** [comment]
> > 那个是另一个插件，已经废弃了，目前的apk会下个版本开源，会加上新功能，感谢关注
> 
> 感谢回复，期待~

https://github.com/SonicCloudOrg/sonic-android-apk
