### ISSUE TITLE
feat: 权限管理

### ISSUE THREAD

**Issue by yaming116** [SonicCloudOrg/sonic-server#139]
## 全局身份

- 管理员
  - 管理用户
     - 删除用户
  - 管理设备
    -  删除无效设备
  - 管理 agent
    - 添加和删除 agent
- 普通用户
  - 正常功能使用和新建项目

## 项目
- 项目管理员
  - 管理项目人员，包括添加管理员、编辑者、查看人员
  - 删除项目权限
- 编辑者
  - 正常使用，包括编写用例等一切写的权限
- 查看者
  - 只有读的权限

**Comment by ZhouYixun** [comment]
> ## 全局身份
> * 管理员
>   
>   * 管理用户
>     
>     * 删除用户
>   * 管理设备
>     
>     * 删除无效设备
>   * 管理 agent
>     
>     * 添加和删除 agent
> * 普通用户
>   
>   * 正常功能使用和新建项目
> 
> ## 项目
> * 项目管理员
>   
>   * 管理项目人员，包括添加管理员、编辑者、查看人员
>   * 删除项目权限
> * 编辑者
>   
>   * 正常使用，包括编写用例等一切写的权限
> * 查看者
>   
>   * 只有读的权限

全局-> 管理员->管理设备 加多一个可以强制释放正在占用的设备，对应逻辑后面在做。
全局-> 管理员->管理agent 加多一个key只能管理员可见

应该不用区分全局和项目
应该只需要管理员（项目管理员的也包含进去）、普通用户
至于普通用户可以配置是否可以编辑、是否可以访问项目等等可能追溯到接口增删查改层面的权限了

@JayWenStar WDYT?

**Comment by yaming116** [comment]
全局管理员默认有全部想的管理权限，如果不区分项目这个权限分配给过多的人有点过大
如果普通用户设置是否可以编辑其实就是编辑者和查看着两个权限

**Comment by JayWenStar** [comment]
> > ## 全局身份
> > 
> > * 管理员
> >   
> >   * 管理用户
> >     
> >     * 删除用户
> >   * 管理设备
> >     
> >     * 删除无效设备
> >   * 管理 agent
> >     
> >     * 添加和删除 agent
> > * 普通用户
> >   
> >   * 正常功能使用和新建项目
> > 
> > ## 项目
> > 
> > * 项目管理员
> >   
> >   * 管理项目人员，包括添加管理员、编辑者、查看人员
> >   * 删除项目权限
> > * 编辑者
> >   
> >   * 正常使用，包括编写用例等一切写的权限
> > * 查看者
> >   
> >   * 只有读的权限
> 
> 全局-> 管理员->管理设备 加多一个可以强制释放正在占用的设备，对应逻辑后面在做。 全局-> 管理员->管理agent 加多一个key只能管理员可见
> 
> 应该不用区分全局和项目 应该只需要管理员（项目管理员的也包含进去）、普通用户 至于普通用户可以配置是否可以编辑、是否可以访问项目等等可能追溯到接口增删查改层面的权限了
> 
> @JayWenStar WDYT?

不知道我理解有没有问题，感觉权限控制得太粗了，属于某个角色就能操作所有。  
另外对于项目，只查看不编辑的情况应该是不存在的，对于自己不相关的项目，查看也没啥意义，无关项目太多反而干扰视觉；做成Yapi那种把人拉进项目就能直接编辑的就好。

**Comment by ZhouYixun** [comment]
> > > ## 全局身份
> > > 
> > > * 管理员
> > >   
> > >   * 管理用户
> > >     
> > >     * 删除用户
> > >   * 管理设备
> > >     
> > >     * 删除无效设备
> > >   * 管理 agent
> > >     
> > >     * 添加和删除 agent
> > > * 普通用户
> > >   
> > >   * 正常功能使用和新建项目
> > > 
> > > ## 项目
> > > 
> > > * 项目管理员
> > >   
> > >   * 管理项目人员，包括添加管理员、编辑者、查看人员
> > >   * 删除项目权限
> > > * 编辑者
> > >   
> > >   * 正常使用，包括编写用例等一切写的权限
> > > * 查看者
> > >   
> > >   * 只有读的权限
> > 
> > 
> > 全局-> 管理员->管理设备 加多一个可以强制释放正在占用的设备，对应逻辑后面在做。 全局-> 管理员->管理agent 加多一个key只能管理员可见
> > 应该不用区分全局和项目 应该只需要管理员（项目管理员的也包含进去）、普通用户 至于普通用户可以配置是否可以编辑、是否可以访问项目等等可能追溯到接口增删查改层面的权限了
> > @JayWenStar WDYT?
> 
> 不知道我理解有没有问题，感觉权限控制得太粗了，属于某个角色就能操作所有。 另外对于项目，只查看不编辑的情况应该是不存在的，对于自己不相关的项目，查看也没啥意义，无关项目太多反而干扰视觉；做成Yapi那种把人拉进项目就能直接编辑的就好。

那全局管理员其实更趋向是运维或者总监身份的了，项目管理员就是分配个各个项目的负责人，普通用户就是再往下细分权限

**Comment by ZhouYixun** [comment]
> 全局管理员默认有全部想的管理权限，如果不区分项目这个权限分配给过多的人有点过大 如果普通用户设置是否可以编辑其实就是编辑者和查看着两个权限

构思这个可以慢慢来，但是目前我们有架构重新调整的计划，不知道可不可以先稍等我们调整完呢？

**Comment by yaming116** [comment]
目前重新启动这个需求？两位是想按照固定角色对应权限来做还是RBAC来搞？之前的设计是参考 gitlab 来设计的，目前个人倾向是这种，RBAC 所有都是自定义目前觉得没必要 @ZhouYixun @JayWenStar

**Comment by ZhouYixun** [comment]
> 目前重新启动这个需求？两位是想按照固定角色对应权限来做还是RBAC来搞？之前的设计是参考 gitlab 来设计的，目前个人倾向是这种，RBAC 所有都是自定义目前觉得没必要 @ZhouYixun @JayWenStar

倾向RBAC一点点，毕竟用户口味难调整。。
