### ISSUE TITLE
【Help】请问能否分享下Dockerfile？

### ISSUE THREAD

**Issue by JinHaoIsHere** [SonicCloudOrg/sonic-server#201]
如题，想参考下运行环境搭建的过程，和镜像的构建方法

**版本**
Sonic的版本号 | Sonic's Version. 
部署的系统(mac,windows32...) |  System

**Comment by ZhouYixun** [comment]
> 如题，想参考下运行环境搭建的过程，和镜像的构建方法
> 
> **版本** Sonic的版本号 | Sonic's Version. 部署的系统(mac,windows32...) | System

已经内置在代码里了，你可以找找看

**Comment by JinHaoIsHere** [comment]
> > 如题，想参考下运行环境搭建的过程，和镜像的构建方法
> > **版本** Sonic的版本号 | Sonic's Version. 部署的系统(mac,windows32...) | System
> 
> 已经内置在代码里了，你可以找找看

能麻烦指一下路吗？sonic-server的Dockerfile
