### ISSUE TITLE
Suggestion - PDF for the overall guide for sonic in English

### ISSUE THREAD

**Issue by pushpeshkarki** [SonicCloudOrg/sonic-server#242]
I am currently located in India, and it's quite difficult to visit the sonic official site to read through the documentation due to restrictions on Chinese websites. Just to get started, can either the documentation be hosted on GitHub or have another URL located on a neural location that we can access more easily? Can we have a PDF file with all the information to start with Sonic?

You guys are doing great with this, and I would request you all to think about how you can make this information more reachable to everyone so that we can grow the sonic community and take it forward in the future.

Kindly let me know if I can be of any help in this process.

Cheers,
Pushpesh

**Comment by ZhouYixun** [comment]
Thank you for your support to sonic! 
Since sonic has been open source for less than one year, most of our articles and codes are in Chinese. However, we are currently planning to internationalize. As for the official website, we can host one in GitHub in the near future, so that non Chinese Mainland users can easily access it.

**Comment by ZhouYixun** [comment]
hello @pushpeshkarki 
I switched the static resource proxy site of the website. Can you directly access the official website with the Indian network now?

**Comment by pushpeshkarki** [comment]
> hello @pushpeshkarki I switched the static resource proxy site of the website. Can you directly access the official website with the Indian network now?

Hi,

I have verified the same. The site is accessible now. Thanks for the quick turnaround.

**Comment by ZhouYixun** [comment]
> 

ok，English is comming soon. Thank you for your support!

**Comment by pushpeshkarki** [comment]
Thanks for the quick turnaround, looking forward to English version.

**Comment by ZhouYixun** [comment]
> Thanks for the quick turnaround, looking forward to English version.

At present, 30-35% of the texts in the project have not been translated. We plan to complete the translation from January to February 2023, and then plan to complete the translation on the official website, hoping to complete it from March to April

**Comment by ZhouYixun** [comment]
> Author

It's been a difficult process, we're working hard to build, this is part of what we've done, you can view https://sonic-cloud.cn/en/deploy/back-end-deploy.html and more.

**Comment by pushpeshkarki** [comment]
Hi,

Can you confirm is the link mentioned is correct as it is not accessible?

**Comment by ZhouYixun** [comment]
> Hi,
> 
> Can you confirm is the link mentioned is correct as it is not accessible?

Oh,  We have deployed our official website in a new domain name, and the old domain name will be gradually deprecated. Thank you for waiting   https://soniccloudorg.github.io/en/deploy/back-end-deploy.html
