### ISSUE TITLE
【Bug】控件详情滚动底部显示不完整

### ISSUE THREAD

**Issue by lr145251** [SonicCloudOrg/sonic-server#268]
**在提出此issue时，我确认了以下几点（保存后请点击复选框）：**

- [x] 我已自己确认这是Sonic自身的Bug。
- [x] 我接受此issue可能被关闭，并查看开发人员的建议。

**Bug 描述**
清晰地描述Bug的情况与详细复现步骤 | A clear and concise description of what the bug is.
![image](https://user-images.githubusercontent.com/50194250/198253505-8772798b-d1c2-4dcc-ba2c-3ae2b98da328.png)

**版本**
Sonic2.0bate
部署的系统(mac,windows32...) | centos7

**Comment by ZhouYixun** [comment]
好的，建议可以前往社区提bug，那边响应和反馈快一点

**Comment by ZhouYixun** [comment]
已经解决了 v2.0.3
