### ISSUE TITLE
【Bug】非首页跳转设备中心，左侧导航栏隐藏未展示

### ISSUE THREAD

**Issue by lr145251** [SonicCloudOrg/sonic-server#269]
**在提出此issue时，我确认了以下几点（保存后请点击复选框）：**

- [x] 我已自己确认这是Sonic自身的Bug。
- [x] 我接受此issue可能被关闭，并查看开发人员的建议。

**Bug 描述**
![image](https://user-images.githubusercontent.com/50194250/198255928-964dee11-91d6-4c41-a102-8ea1934d1ca9.png)
**版本**
Sonic2.0.0bate
部署的系统(mac,windows32...) |  centos

**Comment by ZhouYixun** [comment]
这个没有问题，项目里面点有就行了，其他页面点就是返回这里的
