### ISSUE TITLE
【feat】添加jenkins配置

### ISSUE THREAD

**Issue by shinyvince** [SonicCloudOrg/sonic-server#273]
在持续集成设置那里，加个Jenkins配置（账户or token、产物上传sonic开关）

大公司每天编译次数上百上千很正常，一个apk还上百兆，现有产物直接上传到sonic服务器的设计不够友好，sonic-server服务器吃不消。

**Comment by ZhouYixun** [comment]
请提到 https://github.com/jenkinsci/sonic-ci-helper-plugin
