### ISSUE TITLE
【feat】用例功能优化建议

### ISSUE THREAD

**Issue by aoliaoaoaojiao** [SonicCloudOrg/sonic-server#274]
1.增加获取节点列表功能，获取到一组特定的node节点，配合while功能迭代
2.poco增加根据node属性判断操作
3.增加变量操作相关，如执行过程中变量重新赋值操作
4.poco增加settext接口
5.增加打印功能，配合类似while功能将关键节点信息打印到日志中

**Comment by ZhouYixun** [comment]
Done.
