### ISSUE TITLE
【feat】Telegram 电报机器人及其他机器人

### ISSUE THREAD

**Issue by ayumi760405** [SonicCloudOrg/sonic-server#282]
我想增加Telegram电报和其他机器人，也调整一下RobotMsgTool结构，随着机器人越来越多，都放同一个类不易维护。

**Comment by ZhouYixun** [comment]
> 我想增加Telegram电报和其他机器人，也调整一下RobotMsgTool结构，随着机器人越来越多，都放同一个类不易维护。

不错的想法，可以将机器人方法抽象为interface，然后不同机器人impl去实现

**Comment by ZhouYixun** [comment]
> 我想增加Telegram电报和其他机器人，也调整一下RobotMsgTool结构，随着机器人越来越多，都放同一个类不易维护。

你好，不知是否方便顺便补充Telegram机器人的配置文档呢？ https://github.com/SonicCloudOrg/sonic-offical-website/edit/main/src/markdown/doc/doc-robot.md

**Comment by ayumi760405** [comment]
> > 我想增加Telegram电报和其他机器人，也调整一下RobotMsgTool结构，随着机器人越来越多，都放同一个类不易维护。
> 
> 你好，不知是否方便顺便补充Telegram机器人的配置文档呢？ https://github.com/SonicCloudOrg/sonic-offical-website/edit/main/src/markdown/doc/doc-robot.md

好的，我再來補充。

**Comment by ZhouYixun** [comment]
> > > 我想增加Telegram电报和其他机器人，也调整一下RobotMsgTool结构，随着机器人越来越多，都放同一个类不易维护。
> > 
> > 
> > 你好，不知是否方便顺便补充Telegram机器人的配置文档呢？ https://github.com/SonicCloudOrg/sonic-offical-website/edit/main/src/markdown/doc/doc-robot.md
> 
> 好的，我再來補充。

感谢～ 官网文档补充还是很方便的，直接页面编辑就差不多了
