### ISSUE TITLE
feat：增加套件参数

### ISSUE THREAD

**Issue by GFB214** [SonicCloudOrg/sonic-server#302]
在提出此拉取请求时，我确认了以下几点（保存后请点击复选框）：

-  [x] 标题为fix、feat或doc开头
 - [x] 我已检查没有与此请求重复的拉取请求。
 - [x] 我已经考虑过，并确认这份呈件对其他人很有价值。
 - [x] 我接受此提交可能不会被使用，并根据维护人员的意愿关闭拉取请求。
填写PR内容：增加套件参数

**Comment by ZhouYixun** [comment]
我感觉给套件配置特定参数，和全局参数直接命名来区分差别不是很大

**Comment by ZhouYixun** [comment]
或者改成套件可以配置传入哪些全局参数进去都可以（默认传入所有参数），但是你这样新开一个表感觉作用不是特别大，你觉得呢？

**Comment by ZhouYixun** [comment]
该需求后续在这里讨论交流~ 其他pr和issue我先关闭了
