### ISSUE TITLE
使用 LDAP 作为认证数据库，认证失败，日志报： LDAP: error code 32 - No Such Object

### ISSUE THREAD

**Issue by qixiangyang** [SonicCloudOrg/sonic-server#306]
**在提出此issue时，我确认了以下几点（保存后请点击复选框）：**

**Bug 描述**
使用 LDAP 作为认证数据库，认证失败，日志报：
LDAP: error code 32 - No Such Object

**版本**
2.2.1

配置文件：
LDAP_USER_ENABLE=true
LDAP_USER_ID=cn
LDAP_BASE_DN=ou=people
LDAP_BASE=ou=people
LDAP_USERNAME=cn=admin,ou=people
LDAP_PASSWORD=xxx
LDAP_URL=ldap://xxx.xxx.x.x:389
LDAP_OBJECT_CLASS=inetOrgPerson

**Comment by ZhouYixun** [comment]
请问切换2.0.0有这个问题吗？

**Comment by ZhouYixun** [comment]
> LDAP_BASE_DN=ou=people
LDAP_BASE=ou=people

这里配置貌似不对，你将LDAP_BASE设置为空字符串试试看

**Comment by qixiangyang** [comment]
收到，我试试

**Comment by ZhouYixun** [comment]
> 收到，我试试

https://stackoverflow.com/questions/24777707/spring-security-issue-with-ldap-error-code-32-no-such-object 帮你大概翻了下，感觉是LDAP设置的问题，你可以附上你们的配置看看

**Comment by qixiangyang** [comment]
LDAP_BASE 设置为空字符后，可以认证成功，谢谢啦

**Comment by ZhouYixun** [comment]
> LDAP_BASE 设置为空字符后，可以认证成功，谢谢啦

好的~ 我也记录一下这个报错，后面其他人遇到让他看这里
