### ISSUE TITLE
希望部署能支持https，当前后端处理链接很多都写死为http

### ISSUE THREAD

**Issue by mocobk** [SonicCloudOrg/sonic-server#327]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

v2.3.0

### Deploy platform

Linux

### Minimal reproduce step

如新建项目上传项目logo后无法访问
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/26194964/227751023-2f81be37-58b1-483e-a692-e51b04077b03.png">

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
一般内部局域网搭建不用走https吧，而且还要处理agent的wss，很麻烦的

**Comment by ZhouYixun** [comment]
这个未来不一定会支持，我先关闭这个issue吧，等后面有计划了再reopen
