### ISSUE TITLE
[Bug] 2.4.1-release 版本数据库还是无法初始化

### ISSUE THREAD

**Issue by bobzzb** [SonicCloudOrg/sonic-server#330]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.4.1 版本无法初始化数据库
2.3.2可以初始化数据库

### Deploy platform

linux

### Minimal reproduce step

执行mvn package 无法初始化数据库

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
mvn package并不会初始化数据库哦，请按照官网文档部署
