### ISSUE TITLE
[Bug] 通过REST API占用设备并获取远程，不能立即使用连接

### ISSUE THREAD

**Issue by mocobk** [SonicCloudOrg/sonic-server#368]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.1

### Deploy platform

Macosx

### Minimal reproduce step

1. 用 REST API 获取 uia2 连接地址
2. 在脚本中立即使用 uia2 地址初始化 AndroidDriver
3. 执行方法会出现报错情况

获取 uia2 地址需要强制等待设备 server 启动完成，建议这里做成阻塞式接口或能获取是否启动完成的状态，避免脚本强制等待一个时间

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
这还真不太好做，，不错的建议。我看看怎么优化比较好

**Comment by mocobk** [comment]
采用了client 轮询的方式临时解决了
```python
    def wait_remote_server_ready(remote_url, timeout=30):
        """等待远程服务准备好"""
        time_start = time.time()
        while time.time() - time_start <= timeout:
            time.sleep(1)
            logger.debug('check remote server status...')
            response = request_with_proxy('GET', remote_url + '/status')
            if response.status_code != 200:
                continue
            result = response.json()
            if result.get('value', {}).get('ready'):
                logger.info(f'{result["value"].get("message")}')
                return
        raise TimeoutError('wait remote server ready timeout')
```
