### ISSUE TITLE
[Question] mac部署完成服务端接口502

### ISSUE THREAD

**Issue by liwenliali** [SonicCloudOrg/sonic-server#397]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

![image](https://github.com/SonicCloudOrg/sonic-server/assets/39513637/83b56a6c-786e-48f9-aca5-d35a088ba3a1)
https://sonic-cloud.cn/deploy/back-end-deploy.html
根据此文档部署

### Deploy platform

macpro M1 芯片

### Minimal reproduce step

![image](https://github.com/SonicCloudOrg/sonic-server/assets/39513637/83b56a6c-786e-48f9-aca5-d35a088ba3a1)
https://sonic-cloud.cn/deploy/back-end-deploy.html
根据此文档部署

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
请提供controller日志

**Comment by liwenliali** [comment]
[sonic-server-controller.log](https://github.com/SonicCloudOrg/sonic-server/files/13750778/sonic-server-controller.log)
开始时mysql连接失败了，后面我修改了mysql配置，rm了容器重新初始化创建，报以上错误

**Comment by liwenliali** [comment]
看起来重新初始化之后没有创建数据库和相关表，请问这个要如何继续操作呢

**Comment by ZhouYixun** [comment]
> [sonic-server-controller.log](https://github.com/SonicCloudOrg/sonic-server/files/13750778/sonic-server-controller.log) 开始是mysql连接失败了，后面我修改了mysql配置，rm了容器重新初始化创建，报以上错误

这没看到报错，另外不建议使用m1部署

**Comment by Acheng97** [comment]
Mac m2能部署吗

**Comment by liwenliali** [comment]
> > [sonic-server-controller.log](https://github.com/SonicCloudOrg/sonic-server/files/13750778/sonic-server-controller.log) 开始是mysql连接失败了，后面我修改了mysql配置，rm了容器重新初始化创建，报以上错误
> 
> 这没看到报错，另外不建议使用m1部署

后面重启了一下等了一会儿又正常了，M1部署可以正常使用

**Comment by liwenliali** [comment]
> Mac m2能部署吗

M1可以，M2应该也可以的，但是上面说不建议mac部署
