### ISSUE TITLE
[Question] 用户社区无法访问了

### ISSUE THREAD

**Issue by gradient30** [SonicCloudOrg/sonic-server#404]
### Search before asking

- [ ] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

最近的

### Deploy platform

无

### Minimal reproduce step

无
![11](https://github.com/SonicCloudOrg/sonic-server/assets/39947529/917c0c15-bee4-4ba0-9f91-522ce3e86538)
![22](https://github.com/SonicCloudOrg/sonic-server/assets/39947529/3eed068a-5c39-400b-8d84-2fd71bcae735)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
其他人没反馈这个，你检查下是不是你discord账户有问题？

**Comment by jeniva** [comment]
现在社区需要啥网络访问呢，我这边也打不开
![image](https://github.com/SonicCloudOrg/sonic-server/assets/8514029/4c327442-6810-4757-beed-18b602ec1bb8)

**Comment by gradient30** [comment]
> 现在社区需要啥网络访问呢，我这边也打不开 ![image](https://private-user-images.githubusercontent.com/8514029/295765191-4c327442-6810-4757-beed-18b602ec1bb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5MzkwMjksIm5iZiI6MTcwNDkzODcyOSwicGF0aCI6Ii84NTE0MDI5LzI5NTc2NTE5MS00YzMyNzQ0Mi02ODEwLTQ3NTctYmVlZC0xOGI2MDJlYzFiYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMDIwNTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTMwNjQ1MzQzYmJmODdjMmUzNzEwNDAxYTM3YjVjYmY0MGQyMWFjNTUzNGY0MWJiNTBmZjI4NTA3NWRkMTY5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FxstTNG5tRgm5l089nQg3H-Yr9aMDbE2dI_kFvxJwrk)

你得先注册并登录discord帐号

**Comment by jeniva** [comment]
我是网址都打不开呢，网络访问不了，你们是普通的手机网络都能访问的吗，我试了电脑和手机都不行，我还下载了一个App也进不去。为啥之前的论坛不能访问，现在这个不太方便呢

**Comment by ZhouYixun** [comment]
> 我是网址都打不开呢，网络访问不了，你们是普通的手机网络都能访问的吗，我试了电脑和手机都不行，我还下载了一个App也进不去。为啥之前的论坛不能访问，现在这个不太方便呢

需要科学上网，之前的论坛我们组织已经没有剩余资金可以运营昂贵的香港服务器费用了，所以切到discord

**Comment by jeniva** [comment]
> > 我是网址都打不开呢，网络访问不了，你们是普通的手机网络都能访问的吗，我试了电脑和手机都不行，我还下载了一个App也进不去。为啥之前的论坛不能访问，现在这个不太方便呢
> 
> 需要科学上网，之前的论坛我们组织已经没有剩余资金可以运营昂贵的香港服务器费用了，所以切到discord

好的，这个邀请码也过期了，neng能重新发个链接吗，然后我回到主页一直卡在这个界面
![image](https://github.com/SonicCloudOrg/sonic-server/assets/8514029/ff3a24b1-5543-4d66-a2c2-290e84e3e913)
