### ISSUE TITLE
[Question] 我前端部署在服务器，在本地打开后登陆界面一直转圈圈咋回事啊

### ISSUE THREAD

**Issue by Acheng97** [SonicCloudOrg/sonic-server#405]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.3

### Deploy platform

centos7

### Minimal reproduce step

![1704334708197](https://github.com/SonicCloudOrg/sonic-server/assets/65265814/110214e8-8dae-4e4c-8aa3-e45011ce2bf4)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
可以看下你controller的日志，建议在linux部署

**Comment by Acheng97** [comment]
centos就是Linux，我看了日志，表示太多看不懂，好像是mysql的问题，我mysql配置没问题啊
这是我的配置
<img width="447" alt="image" src="https://github.com/SonicCloudOrg/sonic-server/assets/65265814/d573aeb2-b5a5-4937-8584-bad019643e4f">

**Comment by Acheng97** [comment]
[sonic-server-controller.log](https://github.com/SonicCloudOrg/sonic-server/files/13825357/sonic-server-controller.log)
这是我的日志，麻烦大佬可以给看一下吗

**Comment by ZhouYixun** [comment]
就是mysql没连上，检查下吧。更改.env文件后记得docker-compose down再up
