### ISSUE TITLE
[Question] 请教一下为什么agent和server要在同一个网络环境下，才可以手机投屏显示？

### ISSUE THREAD

**Issue by wz51239925** [SonicCloudOrg/sonic-server#406]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

如标题所问

### Deploy platform

macos 2.6.2

### Minimal reproduce step

咨询问题

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
只需要server能ping到Agent就行，不需要同一个网络，需要同一个网络的是使用者的网络和Agent的网络
