### ISSUE TITLE
[Question] screen websocket bytes流时断时续

### ISSUE THREAD

**Issue by shizhiweiliang** [SonicCloudOrg/sonic-server#412]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.2

### Deploy platform

macosx

### Minimal reproduce step

前端页面websocket通信会出现页面变化的时候正常发送视频流bytes信息 但页面无变化时发送bytes流信息明显减少的问题。可以请教一下这是为什么吗？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
画面没动为什么要发送页面数据？

**Comment by shizhiweiliang** [comment]
请教一下大佬 如果想通过这个websocket来录屏的话怎么能让它持续发送bytes哪怕页面没变啊
