### ISSUE TITLE
[Bug]  无法启动sonic

### ISSUE THREAD

**Issue by fancker1992** [SonicCloudOrg/sonic-server#416]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

服务端：2.6.2
agent：2.6.2

### Deploy platform

服务端：macos
agent : windows

java版本：jdk17

### Minimal reproduce step

本来是想在用户社区提问的，但是用户社区打不开    https://sonic-cloud.wiki/

提问问题报错日志如下：

![img_v3_027f_c82012d2-b40d-4435-a539-e44fb84e5c8g](https://github.com/SonicCloudOrg/sonic-server/assets/24252503/af43998b-cf04-420d-ad52-e90d39e101c7)
![img_v3_027f_97046ff8-1d10-4d92-887a-4b5077fc67cg](https://github.com/SonicCloudOrg/sonic-server/assets/24252503/0f84ea5c-3703-49d4-b02d-9bee6476bfa7)
![img_v3_027f_aeb446d2-2c0a-4a15-9f23-8f0fb74d6b3g](https://github.com/SonicCloudOrg/sonic-server/assets/24252503/87146188-538c-46b1-a641-edc1c4d47582)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
1. 请检查你的yml格式，你也可以发上来
2. 社区地址早改了 从官网进入就可以

**Comment by liuguangyong93** [comment]
> 1. 请检查你的yml格式，你也可以发上来
> 2. 社区地址早改了 从官网进入就可以

请问社区地址是这个嘛？

![image](https://github.com/SonicCloudOrg/sonic-server/assets/15274523/bedc9fa9-c8f7-4e6c-a0db-20d1319e26da)

**Comment by ZhouYixun** [comment]
是的，需要注册discord

**Comment by liuguangyong93** [comment]
> 是的，需要注册discord

注册了，还是不行哎

![image](https://github.com/SonicCloudOrg/sonic-server/assets/15274523/daabea71-3e96-4653-a55b-5096c25308ce)
