### ISSUE TITLE
[Invalid] Diconnected

### ISSUE THREAD

**Issue by AdJIa** [SonicCloudOrg/sonic-server#418]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.3

### Deploy platform

Win10 
sonic-agent-v2.6.3-windows_x86_64

### Minimal reproduce step

* sonic 版本：2.6.3
* 手机设备：Redmi Note 11 5G China
* miui：14.0.4
* sonic server 版本 ： sonic-server-v263
* sonic server 环境 ： mac docker 
*  agent 版本: sonic-agent-v2.6.3-windows_x86_64
* agent  环境： win10

---

1. 按照server、agent、设备接入文档 接入后显示：
 【图1】<img width="504" alt="1706972627294" src="https://github.com/SonicCloudOrg/sonic-server/assets/13943009/7e5c87e1-9cd8-42ce-9e67-268e8979c1d8">
 
2. 点击马上使用之后  一直转圈， 手机也未安装任何apk 
【图2】<img width="1883" alt="1706972413646" src="https://github.com/SonicCloudOrg/sonic-server/assets/13943009/11959515-f7f1-4824-8522-07dcfbb9a436">

PS. 尝试过手动安装 Sonic插件、uiautomator2、uiautomator2-test 后 点击马上使用依然如图2

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by AdJIa** [comment]
另外 用户社区邀请加入的链接 点击显示 无法接受链接

**Comment by AdJIa** [comment]
help me ths

**Comment by ZhouYixun** [comment]
你可以检查Agent ip，防火墙等，至少应该提供一下Agent的log日志

另外社区的链接需要墙

**Comment by AdJIa** [comment]
已加入 感谢 ， 另外上述问题 今天换了agent 和 server 都在mac 之后 得到解决 ，手机配置未调整 ，排除判断应该是 agent 部署的问题 @ZhouYixun
