### ISSUE TITLE
[QUESTION] 请教MySQL连接不上问题

### ISSUE THREAD

**Issue by liuguangyong93** [SonicCloudOrg/sonic-server#424]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

v2.6.4

### Deploy platform

macbook pro intel core

### Minimal reproduce step

![image](https://github.com/SonicCloudOrg/sonic-server/assets/15274523/769efecb-a4ec-4238-bb64-01a59901b78e)

参照文档本地mac上运行项目，出现上述问题导致项目暂时无法使用

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by liuguangyong93** [comment]
跟mysql这个日志提示有关系吗？

![image](https://github.com/SonicCloudOrg/sonic-server/assets/15274523/a79ede72-98a5-4fee-8c05-973a648e2513)

**Comment by liuguangyong93** [comment]
![image](https://github.com/SonicCloudOrg/sonic-server/assets/15274523/88419866-c23b-4947-8258-7da4dc0694cb)

**Comment by liuguangyong93** [comment]
mysql容器不能启动的问题解决了，但是现在还是报503，麻烦帮我看一下这个问题

![image](https://github.com/SonicCloudOrg/sonic-server/assets/15274523/6ba6738d-6a3a-41f3-a3ca-411b0a2a5d01)

**Comment by ZhouYixun** [comment]
一般不推荐docker起mysql，你可以自己本地起一个，建表的字符集和排序规则看一下文档

**Comment by liuguangyong93** [comment]
> 一般不推荐docker起mysql，你可以自己本地起一个，建表的字符集和排序规则看一下文档

我本地自己起了一个mysql，还是如此，不知所措了

<img width="1271" alt="image" src="https://github.com/SonicCloudOrg/sonic-server/assets/15274523/eb5c1c40-dab1-4a6b-b21d-06eeeabaa121">
![image](https://github.com/SonicCloudOrg/sonic-server/assets/15274523/40710389-3e27-4730-8850-9e6dda1433d3)
![image](https://github.com/SonicCloudOrg/sonic-server/assets/15274523/0fa9c9db-69fa-4a1b-9fb3-f8951f04a386)
![image](https://github.com/SonicCloudOrg/sonic-server/assets/15274523/c7e5399d-7804-4265-8fae-cb83566e8ccc)

**Comment by liuguangyong93** [comment]
> 
![image](https://github.com/SonicCloudOrg/sonic-server/assets/15274523/4fc42516-1dcb-46e8-a72e-03c475b85a8f)

**Comment by liuguangyong93** [comment]
![image](https://github.com/SonicCloudOrg/sonic-server/assets/15274523/a419255c-e16e-442c-a4c0-c14787965752)
![image](https://github.com/SonicCloudOrg/sonic-server/assets/15274523/65ed7593-a21f-4ccb-956a-6d10b0bf132e)

**Comment by liuguangyong93** [comment]
> > 一般不推荐docker起mysql，你可以自己本地起一个，建表的字符集和排序规则看一下文档
> 
> 我本地自己起了一个mysql，还是如此，不知所措了
> 
> ![image](https://private-user-images.githubusercontent.com/15274523/308040858-eb5c1c40-dab1-4a6b-b21d-06eeeabaa121.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTE2ODAsIm5iZiI6MTcwOTAxMTM4MCwicGF0aCI6Ii8xNTI3NDUyMy8zMDgwNDA4NTgtZWI1YzFjNDAtZGFiMS00YTZiLWIyMWQtMDZlZWVhYmFhMTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA1MjMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMWI3NzE2Yzk2ZmNkMjdmMGUzY2VkYWJlZTRhNmFmZThjMTBiYzRlMjNlZWVhMGI1Nzc0NjliZWY0MDhjYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aDqGdJV0A5BFP5gJWcMjqoIOVTflezHF1Q5uBOUq7-g) ![image](https://private-user-images.githubusercontent.com/15274523/308041183-40710389-3e27-4730-8850-9e6dda1433d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTE2ODAsIm5iZiI6MTcwOTAxMTM4MCwicGF0aCI6Ii8xNTI3NDUyMy8zMDgwNDExODMtNDA3MTAzODktM2UyNy00NzMwLTg4NTAtOWU2ZGRhMTQzM2QzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA1MjMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmNWE0YWZlMGJiZTAyZDBlNzc2ZWM3MzUyYmUwODFkM2E2NzE3NjAyOGE3NTJiMjJhZWMwYTc4NWY0N2MyYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.asJUIK0RJNafyKKJk5K1Qw3UP8kshFe8UH_EWV4PJcI) ![image](https://private-user-images.githubusercontent.com/15274523/308041380-0fa9c9db-69fa-4a1b-9fb3-f8951f04a386.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTE2ODAsIm5iZiI6MTcwOTAxMTM4MCwicGF0aCI6Ii8xNTI3NDUyMy8zMDgwNDEzODAtMGZhOWM5ZGItNjlmYS00YTFiLTlmYjMtZjg5NTFmMDRhMzg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA1MjMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NzU1NzAwYjM1NDU1Y2EwYmJkNzNhMWViOTMxMTNlOGQ5MGVmOGQ5YmRmNDY5NGRmNzBkOTRlNWU0Njc3YTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CN_yyrsrvLLr_EWBy2JxZHvgSdW9QBBZNRIkwOxVEX8) ![image](https://private-user-images.githubusercontent.com/15274523/308041419-c7e5399d-7804-4265-8fae-cb83566e8ccc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTE2ODAsIm5iZiI6MTcwOTAxMTM4MCwicGF0aCI6Ii8xNTI3NDUyMy8zMDgwNDE0MTktYzdlNTM5OWQtNzgwNC00MjY1LThmYWUtY2I4MzU2NmU4Y2NjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA1MjMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkNWQ2MWZiZjRlMjhlYzUyYTAxMWI4OGI5Mzk1MDgzOWU5NTAwZTg1MzY4NWQyMjM1YTM1ZTU5ZDFlYTRiMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nIi72e9l-YEZo8mEOwMN7C1HxnGE4morI5QQcE9qU-g)

@ZhouYixun

**Comment by ZhouYixun** [comment]
你建表的字符集是什么

**Comment by wen-xue-bee** [comment]
请教下小程序ui自动化过程中，当切换到webview 后 再也无法通过android 的原生元素，需要重新链接手机设备才能重新识别andorid 的原生元素，用过不同的微信版本也一样的情况，请问如何解决@ZhouYixun

**Comment by feiyuxuelang** [comment]
> 解决了，公司内网问题。我使用热点就没问题了。感谢 [@ZhouYixun](https://github.com/ZhouYixun) 大佬

请教下mysql的版本有要求吗，必须是5.7吗
