### ISSUE TITLE
[QUESTION] 机子能够链接上agent，但是就报了错，具体错误信息“cn.hutool.http.HttpException: Read timed out”，页面是弹了错误提示“获取元素控件失败，请重新获取啊”

### ISSUE THREAD

**Issue by q997826952** [SonicCloudOrg/sonic-server#427]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

docker 部署的2.6.3，server和agent都是

### Deploy platform

linux

### Minimal reproduce step

你好，首先很高兴能使用sonic做ui自动化，感谢大佬开源，但是我们遇到了一点问题，我们用的是docker构建的2.6.3版本，客户端是用的windows10，目前只有Redmi Note 10 在获取元素控件是正常的其他的机型全部都报了超时，机子能够链接上agent，但是就报了错，具体错误信息“cn.hutool.http.HttpException: Read timed out”，页面是弹了错误提示“获取元素控件失败，请重新获取啊”，发现报错的机型系统版本都在12以上，麻烦帮忙看下是什么原因引起的

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
请问有按照这里设置吗 https://sonic-cloud.cn/deploy/android-deploy.html#%E5%B0%8F%E7%B1%B3
