### ISSUE TITLE
异常信息： org.cloud.sonic.driver.common.tool.SonicRespException: Cannot invoke "org.openqa.selenium.chrome.ChromeDriver.findElement(org.openqa.selenium.By)" because "this.chromeDriver" is null ----请问这个报错怎么解决[Bug] 

### ISSUE THREAD

**Issue by wen-xue-bee** [SonicCloudOrg/sonic-server#428]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

异常信息： org.cloud.sonic.driver.common.tool.SonicRespException: Cannot invoke "org.openqa.selenium.chrome.ChromeDriver.findElement(org.openqa.selenium.By)" because "this.chromeDriver" is null

### Deploy platform

异常信息： org.cloud.sonic.driver.common.tool.SonicRespException: Cannot invoke "org.openqa.selenium.chrome.ChromeDriver.findElement(org.openqa.selenium.By)" because "this.chromeDriver" is null

### Minimal reproduce step

异常信息： org.cloud.sonic.driver.common.tool.SonicRespException: Cannot invoke "org.openqa.selenium.chrome.ChromeDriver.findElement(org.openqa.selenium.By)" because "this.chromeDriver" is null

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
该填的信息都懒得填？直接复制粘贴？

**Comment by ZhouYixun** [comment]
你修改下提问内容，整理好信息先吧。
