### ISSUE TITLE
[Bug] sonic用几天后系统变慢，模块信息刷新不出来，等待几秒或十几秒才能刷新出来

### ISSUE THREAD

**Issue by sky88601** [SonicCloudOrg/sonic-server#429]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

sonic版本v2.6.4

### Deploy platform

CentOS Linux release 7.8.2003 (Core)

### Minimal reproduce step

sonic用几天后系统变慢，页面显示变慢，最明显的就是模块信息刷新不出来，用例中添加步骤，模块信息等待几秒或十几秒才能刷新出来（图片好像上传不了）

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
你是不是内存太低了，这不是sonic的问题
