### ISSUE TITLE
[Question] 请教，在运行的用例时，报错：java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.chrome.ChromeDriver.navigate()" because "this.chromeDriver" is null

### ISSUE THREAD

**Issue by ZeroBugHero** [SonicCloudOrg/sonic-server#437]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

v2.6.4

### Deploy platform

Linux（centos）

### Minimal reproduce step

1、创建刷新页面用例
2、选择设备马上使用
3、选择用例，开始执行

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
chrome内核太新，近期修复

**Comment by ZeroBugHero** [comment]
老师，您好，我这边的webview的Chrome版本是52.0.2743.100，想问下在进行webview里面的元素定位的时候，是需要使用app里面的webview的Chrome版本的驱动，不是本地电脑的浏览器对于的驱动吧
<img width="1034" alt="image" src="https://github.com/SonicCloudOrg/sonic-server/assets/122763218/ad38b548-4e98-4964-b025-f3fc7ea4034a">

**Comment by ZhouYixun** [comment]
> 老师，您好，我这边的webview的Chrome版本是52.0.2743.100，想问下在进行webview里面的元素定位的时候，是需要使用app里面的webview的Chrome版本的驱动，不是本地电脑的浏览器对于的驱动吧 <img alt="image" width="1034" src="https://private-user-images.githubusercontent.com/122763218/328466910-ad38b548-4e98-4964-b025-f3fc7ea4034a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNzgwMzgsIm5iZiI6MTcxNTA3NzczOCwicGF0aCI6Ii8xMjI3NjMyMTgvMzI4NDY2OTEwLWFkMzhiNTQ4LTRlOTgtNDk2NC1iMDI1LWYzZmM3ZWE0MDM0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxMDI4NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTE3ZDk5Y2Y1MmYwNjY5OTg3YWFjMzQwYjY0ZDk0YmUzMTE4ZjU5OWQ3YTQ5NDQ5NGIyODM2N2U0YWU4MTI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.D89jEofttIzQn2596jZYQTuKvf3GE9wdzc8THVkkzj0">

https://sonic-cloud.cn/doc/doc-to-webview.html#%E5%85%B3%E4%BA%8Echromedriver

**Comment by ZeroBugHero** [comment]
按照文档添加了，在运行的时候还是报错
<img width="854" alt="image" src="https://github.com/SonicCloudOrg/sonic-server/assets/122763218/6c5a93af-8349-4548-a9c1-3096ee9fe6e2">
<img width="1221" alt="image" src="https://github.com/SonicCloudOrg/sonic-server/assets/122763218/975dec9a-0b37-462e-ba83-ab86714ed464">
