### ISSUE TITLE
[Bug] 在内网机器部署后使用内网穿透映射到公网

### ISSUE THREAD

**Issue by wxyShine** [SonicCloudOrg/sonic-server#439]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

v2.6.4

### Deploy platform

Linux  debian12

### Minimal reproduce step

部署成功使用内网 http://192.168.1.223:3000/ 正常使用，  使用frp 将3000端口映射到公网后使用出现问题： 样式文件都没问题 发现一个接口请求的还是内网地址
![image](https://github.com/SonicCloudOrg/sonic-server/assets/42802152/fdab3073-177e-4fc3-8026-de3394440969)

![image](https://github.com/SonicCloudOrg/sonic-server/assets/42802152/46e237bc-b822-4d2a-8270-faf91da15e8c)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by YeungHoiChiu** [comment]
web 请求的baseURL就是走的内网，项目本来应用场景就是局域网云真机，所以你需要二次开发。
<img width="612" alt="image" src="https://github.com/SonicCloudOrg/sonic-server/assets/44832826/610e63f0-c311-4fd9-88b5-877499c63862">

.env 
![image](https://github.com/SonicCloudOrg/sonic-server/assets/44832826/f71801d5-fb45-43fc-b758-66248ef4a979)

而且如果修改成https的话，之前在社区群内看到有说ws也会走wss，可能会导致无法使用真机
