### ISSUE TITLE
[Bug] 官网无法访问了

### ISSUE THREAD

**Issue by bosen365** [SonicCloudOrg/sonic-server#441]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

官网无法访问了

### Deploy platform

官网无法访问了

### Minimal reproduce step

官网无法访问了

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
官网被攻击了，查找相关文档可以先从 https://github.com/SonicCloudOrg/sonic-offical-website 搜索
