### ISSUE TITLE
[Bug] 官网目前访问不了

### ISSUE THREAD

**Issue by hotsmile** [SonicCloudOrg/sonic-server#444]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

<Error>
<Code>AccessDenied</Code>
<Message>You have no right to access this object because of bucket acl.</Message>
<RequestId>664D655D9EB6B212B928425B</RequestId>
<HostId>sonic-cloud.oss-accelerate.aliyuncs.com</HostId>
<EC>0003-00000001</EC>
<RecommendDoc>https://api.aliyun.com/troubleshoot?q=0003-00000001</RecommendDoc>
</Error>

### Deploy platform

no deploy

### Minimal reproduce step

no step

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
被攻击了，你可以先访问用户社区
