### ISSUE TITLE
[Bug] 自定义脚本中使用了python脚本，截图功能不可用

### ISSUE THREAD

**Issue by junjunsay** [SonicCloudOrg/sonic-server#463]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

2.6.4

### Deploy platform

mac

### Minimal reproduce step

1.通过前端 添加步骤--->图像操作--->获取截图
2.通过前端 添加步骤--->特殊操作---自定义脚本
3.脚本中
`
from uia2.driver import AndroidDriver
session_id, adb_serial_num, global_pramas, uia_url = sys.argv[1:]
driver = AndroidDriver(uia_url)
driver.close_driver()
`
4.通过前端 添加步骤--->图像操作--->获取截图

表现 第一个截图是正常的，第二个截图是异常

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
这个已经解决啦，是官网文档写错了一个地方，改成这样就好了

```
driver = AndroidDriver(url=uia_url, session_id=session_id)
```
