### ISSUE TITLE
[Question] 请教下，现在项目启动的mysql版本是多少呢，8.0以上好像是都需要有主键的。但是test_suites_devices、public_steps_steps这几张表都没看到有主键，我设置之后启动项目又会删除失败

### ISSUE THREAD

**Issue by MythCoderZ** [SonicCloudOrg/sonic-server#469]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

main

### Deploy platform

win

### Minimal reproduce step

项目初始化启动

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
试试mysql 5.7

**Comment by MythCoderZ** [comment]
5.7版本是可以启动的，那后续有考虑支持8.0版本吗
