### ISSUE TITLE
[Bug] 有在线可试用的版本么

### ISSUE THREAD

**Issue by mlzboy** [SonicCloudOrg/sonic-server#474]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

想看一下0编码UI自动化 积木式创建步骤 一键分发多设备任务

### Deploy platform

想看一下0编码UI自动化 积木式创建步骤 一键分发多设备任务

### Minimal reproduce step

想看一下0编码UI自动化 积木式创建步骤 一键分发多设备任务

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
以前有，但是被人攻击了，现在只能自己手动部署试试看哦~
