### ISSUE TITLE
[Question]请教下大佬，我在一台mac上通过挨个微服务启动的方式部署了sonic-server和sonic-client-web代码，为什么Local:http://localhost:3002/可以访问成功，但是通过Network:  http://30.78.145.132:3002/的方式访问会失败呢？登录面一直在转圈圈。

### ISSUE THREAD

**Issue by pichyyyyy** [SonicCloudOrg/sonic-server#484]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

应该是v2.7.1 （最新的[sonic-server](https://github.com/SonicCloudOrg/sonic-server)代码）

### Deploy platform

Apple M3 Pro
MacOS：14.4.1 (23E224)

### Minimal reproduce step

我修改了sonic-server里的这几个文件代码：
例如本地ip地址为：30.70.100.130

**修改 .env 文件**
SONIC_SERVER_HOST=30.70.100.130
SONIC_SERVER_PORT=3002
MYSQL_HOST=30.70.100.130

**application-eureka.yml文件：**
eureka:
  instance:
    hostname: ${SONIC_EUREKA_HOST:30.70.100.130} 
    ...
    service-url:
      defaultZone: http://${SONIC_EUREKA_USERNAME:sonic}:${SONIC_EUREKA_PASSWORD:sonic}@${SONIC_EUREKA_HOST:30.70.100.130}:${SONIC_EUREKA_PORT:8761}/eureka/

**application-jdbc.yml文件：**
spring:
  datasource:
    ...
    url: jdbc:mysql://${MYSQL_HOST:30.70.100.130}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:sonic}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&serverTimezone=GMT%2b8
    ...

**application-sonic-server-controller.yml 文件：**
host: http://${SONIC_SERVER_HOST:localhost}:${SONIC_SERVER_PORT:3002}

**application-sonic-server-folder.yml文件：**
host: http://${SONIC_SERVER_HOST:localhost}:${SONIC_SERVER_PORT:3002}/server

**application-sonic-server-eureka.yml文件：**
server:
  port: ${SONIC_EUREKA_PORT:8761}
...
    hostname: ${SONIC_EUREKA_HOST:30.70.100.130}  
   
### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
你可以看f12具体报什么错，建议还是按照官网文档部署
