### ISSUE TITLE
[Bug] 鸿蒙4.2.0系统下应用程序列表中未获取到并显示其它安卓应用

### ISSUE THREAD

**Issue by aovenus** [SonicCloudOrg/sonic-server#487]
### Search before asking

- [X] I searched in the issue and found nothing similar. | 我查找了并确认issue列表无相似报告。

### Sonic version

V2.7.2

### Deploy platform

Windows 11下容器化部署

### Minimal reproduce step

鸿蒙4.0系统下应用程序仅读取并显示sonic应用，其它应用未显示
![应用程序列表](https://github.com/user-attachments/assets/ac6bc750-cc2c-432f-96f9-a7e970f71224)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR! | 我将发起PR！

**Comment by ZhouYixun** [comment]
需要给sonic app获取应用的权限
