### ISSUE TITLE
【feat】企业微信机器人&飞书机器人

### ISSUE THREAD

**Issue by ZhouYixun** [SonicCloudOrg/sonic-server#51]
添加其他两种类型机器人

**Comment by ZhouYixun** [comment]
暂时做了飞书机器人，企业微信下一期做

**Comment by impactCn** [comment]
如果还没有做，我可以提供企业微信、钉钉等提醒功能。

**Comment by ZhouYixun** [comment]
> 如果还没有做，我可以提供企业微信、钉钉等提醒功能。

欢迎呀，目前企业微信还没做，如果有意向加入我们组织也可以联系我们

**Comment by impactCn** [comment]
> > 如果还没有做，我可以提供企业微信、钉钉等提醒功能。
> 
> 欢迎呀，目前企业微信还没做，如果有意向加入我们组织也可以联系我们

可以呀，我挺有兴趣做个。

**Comment by ZhouYixun** [comment]
https://github.com/SonicCloudOrg/sonic-server/pull/232
