### ISSUE TITLE
【feat】接入monkey，可获取性能数据

### ISSUE THREAD

**Issue by longyuan94** [SonicCloudOrg/sonic-server#56]

**Comment by linruipei** [comment]
> monkey我自己用随机事件算法完成了，可以在【新增步骤】-》【特殊】-》【随机事件看到】

大佬什么时候接入fastboot的monkey 期待你这个版本

**Comment by ZhouYixun** [comment]
> > monkey我自己用随机事件算法完成了，可以在【新增步骤】-》【特殊】-》【随机事件看到】
> 
> 大佬什么时候接入fastboot的monkey 期待你这个版本

现在可以用自定义脚本实现，官网也有demo例子 https://sonic-cloud.gitee.io/#/Document?tag=runScript
