### ISSUE TITLE
【Doc】求开发环境的文档

### ISSUE THREAD

**Issue by mimajiushi** [SonicCloudOrg/sonic-server#57]
没用过这些环境看起来有些懵逼，有对应文档的话可以让更多人参与开发

**Comment by jahentao** [comment]
我也有基于atxserver2改写的需求，其实atxserver2已经对后续Android10的模拟点击什么的缺乏持续支持了。随着改写的推进，发现了这个使用Java的重构项目，干脆基于这套框架做业务支持，共建共享，不知道目前是否支持的功能进度怎么样了？尤其是对Android/鸿蒙手机的镜像烧录，测试任务下发，调度执行，apk自动化测试方面。

**Comment by ZhouYixun** [comment]
> 我也有基于atxserver2改写的需求，其实atxserver2已经对后续Android10的模拟点击什么的缺乏持续支持了。随着改写的推进，发现了这个使用Java的重构项目，干脆基于这套框架做业务支持，共建共享，不知道目前是否支持的功能进度怎么样了？尤其是对Android/鸿蒙手机的镜像烧录，测试任务下发，调度执行，apk自动化测试方面。

除了镜像烧录，其他功能都有了，安卓10到以上的也支持，可以加群咨询哦

**Comment by suzhenyu006** [comment]
也想出一份力呢~~这个项目的想法真的很不错，希望可以早日更新开发文档~

**Comment by ZhouYixun** [comment]
> 也想出一份力呢~~这个项目的想法真的很不错，希望可以早日更新开发文档~

可以先加我，我这边有个开源群，不过稍微有点门槛

**Comment by suzhenyu006** [comment]
> > 也想出一份力呢~~这个项目的想法真的很不错，希望可以早日更新开发文档~
> 
> 可以先加我，我这边有个开源群，不过稍微有点门槛

可以的，不过哪里可以加你？今天testerhome貌似打不开

**Comment by ZhouYixun** [comment]
> > > 也想出一份力呢~~这个项目的想法真的很不错，希望可以早日更新开发文档~
> > 
> > 
> > 可以先加我，我这边有个开源群，不过稍微有点门槛
> 
> 可以的，不过哪里可以加你？今天testerhome貌似打不开

官网有我二维码，你可以找找看

**Comment by ZhouYixun** [comment]
https://sonic-cloud.gitee.io/#/Contribute 看这里
