### ISSUE TITLE
【feat】增加调试功能，可单步调试

### ISSUE THREAD

**Issue by upengfei** [SonicCloudOrg/sonic-server#58]
在写脚本阶段，比如某个业务操作步骤很多，或者脚本前置条件运行耗时时，如果想验证脚本中间某一步运行是否ok，但又不想每次都从头开始运行脚本，只是运行这一步。 增加该功能后，会大大减少脚本编写时间，提高工作效率。。

**Comment by ZhouYixun** [comment]
2.4.0已实现
