### ISSUE TITLE
【Bug】登录状态下，使用另一个浏览器登录同一个账号，数据库对应密码会清空

### ISSUE THREAD

**Issue by Felix1029** [SonicCloudOrg/sonic-server#94]
**Bug 描述**
同一个账号，已登录的情况下，我使用另一台机子登录同一账号，原账号密码被清空。

**版本**
Sonic的版本号 | Sonic's Version： release 版本
部署的系统： mac
![image](https://user-images.githubusercontent.com/19203666/145945272-0a5f99d0-26a7-48bb-a75d-8c0575b84d55.png)

**Comment by JayWenStar** [comment]
奇怪，这问题我没复现出来，同mac，浏览器是edge + chrome

**Comment by Felix1029** [comment]
> 奇怪，这问题我没复现出来，同mac，浏览器是edge + chrome

你是集群版不，用两台电脑登录一个账号试试？   我等下再试试一台电脑上用chorm 跟safari 看会不会出现

**Comment by JayWenStar** [comment]
> 

是集群版，但没用docker

**Comment by JayWenStar** [comment]
> > 奇怪，这问题我没复现出来，同mac，浏览器是edge + chrome
> 
> 你是集群版不，用两台电脑登录一个账号试试？ 我等下再试试一台电脑上用chorm 跟safari 看会不会出现

是集群版，但没用docker启动

**Comment by JayWenStar** [comment]
破案了，要远控的时候登录才会出现这个bug，复现步骤不全

**Comment by JayWenStar** [comment]
找到原因了，是jpa根据函数名自动更新了user表导致的。

**Comment by JayWenStar** [comment]
跟重新登录无关，只要进入远控就会出现这个问题

**Comment by ZhouYixun** [comment]
后续迁移mybatis-plus

**Comment by JayWenStar** [comment]
问题还在，看来jpa还有问题，下个beta换mybatis-plus预计会解决
