### ISSUE TITLE
【优化】三星设备，手机反应稍微慢些，实际使用勉强接受

### ISSUE THREAD

**Issue by jlintxia** [SonicCloudOrg/sonic-server#96]
**Bug 描述**
【优化】三星设备，手机左右滑动操作等手机反应稍微慢些，实际使用勉强接受，页面帧率目测在顶多30FPS
设置帧率低，也是没有反应快的效果，还是一样慢

**版本**
Sonic的版本号 | v1.2.0-release
部署的系统(mac,windows32...) |  System
安卓设备三星
![image](https://user-images.githubusercontent.com/28779574/145948571-390040ee-5fa7-4509-b727-9c16230a711a.png)

**Comment by ZhouYixun** [comment]
帧率低应该是看起来更慢的

**Comment by ZhouYixun** [comment]
minicap的优化目前算是逐渐定型了，如果这一块部分机型比较慢，应该不打算单独兼容。后续sonic会有scrcpy的方案，你可以尝试用那种方案来远控。我这边先关闭，感谢关注~
